### ISSUE TITLE
Action fails to download terragrunt if latest tag is used

### ISSUE THREAD

**Issue by nadamdb** [autero1/action-terragrunt#161]
In the latest release of terragrunt, v.0.45.9, the name of the release is " v.0.45.9" while the tag is "v.0.45.9" (note the extra space before the name). This causes a problem when the action tries to download the latest terragrunt version, because in line
https://github.com/autero1/action-terragrunt/blob/5b4368f75f1ba035a147619f52a702fd2c7c4f2e/src/action.ts#L45
the name of the release is queried instead of the tag, causing the action to try to download terragrunt from an invalid URL:
`Error: Action failed with "Error: Failed to download Terragrunt from  https://github.com/gruntwork-io/terragrunt/releases/download/ v0.45.9/terragrunt_linux_amd64"
`

The problem can be worked around by using a specific version instead of the latest tag.
A suggestion for a permanent solution would be to use the tag instead of the name in the code above.

**Comment by autero1** [comment]
Fixed in #160
