### ISSUE TITLE
Update to nodejs version 16

### ISSUE THREAD

**Issue by janjongerden-tomtom** [autero1/action-terragrunt#22]
As nodejs 12 has [reached EOL on 2022-04-30](https://github.com/nodejs/release#end-of-life-releases), the project should move to the active LTS version which is 16 at the moment.

**Comment by drey0143143** [comment]
Please how do we fix the warning message below
```
0s
Run autero[1](https://github.com/ipipeline/ipipeline-iam-global-terraform/actions/runs/3237384427/jobs/5304398715#step:5:1)/action-terragrunt@v1.1.0
[INFO] TerragruntVersion: v0.36.2
[INFO] Setting up Terragrunt version: 'v0.36.2'
[INFO] Downloading from: 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.2/terragrunt_linux_amd64'
[INFO] Terragrunt version: 'v0.36.2' has been cached at /opt/hostedtoolcache/terragrunt/0.36.2/x64/terragrunt
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/ipipeline/ipipeline-iam-global-terraform/actions/runs/3237384427/jobs/5304398715#step:5:11)-[11](https://github.com/ipipeline/ipipeline-iam-global-terraform/actions/runs/3237384427/jobs/5304398715#step:5:12)-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mgerlach** [comment]
> Please how do we fix the warning message below
> 
> ```
> Run autero1/action-terragrunt@v1.1.0
> [INFO] TerragruntVersion: v0.36.2
> [INFO] Setting up Terragrunt version: 'v0.36.2'
> [INFO] Downloading from: 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.2/terragrunt_linux_amd64'
> [INFO] Terragrunt version: 'v0.36.2' has been cached at /opt/hostedtoolcache/terragrunt/0.36.2/x64/terragrunt
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022
> ```

set-output is also deprecated, that's a separate issue that needs to be fixed here, too, like the nodejs version

**Comment by autero1** [comment]
Fixed in https://github.com/autero1/action-terragrunt/releases/tag/v1.2.0
