### ISSUE TITLE
Update to use node 20

### ISSUE THREAD

**Issue by bbergenroth** [autero1/action-terragrunt#325]
Node 16 is [EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol/) and GH actions are [transitioning](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by stevie-** [comment]
bump

**Comment by mgerlach** [comment]
Ping?

**Comment by autero1** [comment]
Released in https://github.com/autero1/action-terragrunt/releases/tag/v2.0.0
