### ISSUE TITLE
Upgrade to node 16

### ISSUE THREAD

**Issue by StanHannebelle** [autero1/action-terragrunt#36]
Hello,

Thanks for the great work!

Node 12 has been out of support since April 2022.
This generates a warning in the github actions.

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: autero1/action-terragrunt

Do you plan to update to version 16?

Thanks

**Comment by wanisfahmyDE** [comment]
@StanHannebelle this has been already fixed in release https://github.com/autero1/action-terragrunt/releases/tag/v1.2.0
