### ISSUE TITLE
STDOUT appears when run terragrunt plan after use terragrunt version v0.67.0

### ISSUE THREAD

**Issue by dcarvalhal** [autero1/action-terragrunt#401]
Before:
terraform: No changes. Your infrastructure matches the configuration.
terraform: Terraform has compared your real infrastructure against your configuration
terraform: and found no differences, so no changes are needed.

After:
�[90m18:36:31.341 �[0mSTDOUT �[36mterraform: �[0mNo changes. Your infrastructure matches the configuration.
�[90m18:36:31.341 �[0mSTDOUT �[36mterraform: �[0mTerraform has compared your real infrastructure against your configuration
�[90m18:36:31.341 �[0mSTDOUT �[36mterraform: �[0mand found no differences, so no changes are needed.

**Comment by autero1** [comment]
I believe this is not related to the action, but is a Terraform / Terragrunt issue. Have you tried running with the `-no-color` flag?
